<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Can\'t find published assets for Aii Audio Player extension' 
  => 'Nie mo¿na znaleŸæ upublicznionych plików dla rozszerzenia Aii Audio Player ',
  'JS player file setted by "playerJSFile" property can\'t be empty.' 
  => 'W³aœciwoœæ "playerJSFile" wskazuj¹ca po³o¿enie pliku JS odtwarzacza nie mo¿e byc pusta.',
  'Property "height" can\'t be empty.' 
  => 'W³aœciwoœæ "heigh" opisuj¹ca wysokoœæ nie mo¿e byæ pusta.',
  'Property "width" can\'t be empty.' 
  => 'W³aœciwoœæ "wifth" opisuj¹ca szerokoœæ nie mo¿e byæ pusta.',
  'SWF player file setted by "playerSWFFile" property can\'t be empty.' 
  => 'W³aœciwoœæ "playerSWFFile" wskazuj¹ca po³o¿enie pliku SWF odtwarzacza nie mo¿e byæ pusta.',
);
