<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Core script "{script}" registered.' => 'Core script "{script}" registered.',
  'Css file "{css}" was registered as {registered}.' => 'Css file "{css}" was registered as {registered}.',
  'JS file "{js}" was registered as {registered}.' => 'JS file "{js}" was registered as {registered}.',
  'Level need to be power of 2!' => 'Level need to be power of 2!',
  'No core scripts to register' => 'No core scripts to register',
  'Resource "{res}" published as {published}.' => 'Resource "{res}" published as {published}.',
  'There are no resources to publish.' => 'There are no resources to publish.',
);
