<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Core script "{script}" registered.' => 'Skrypty Ÿród³owe {script} zosta³y zarejestroane.',
  'Css file "{css}" was registered as {registered}.' => 'Plik CSS {css} zosta³ zarejestrowany jako {registered}',
  'JS file "{js}" was registered as {registered}.' => 'Plik JS {js} zosta³ zarejestrowany jako {registered}',
  'Level need to be power of 2!' => 'Poziom musi byæ potêg¹ liczby 2!',
  'No core scripts to register' => 'Nie zarejestrowano ¿adnych skryptów.',
  'Resource "{res}" published as {published}.' => 'ród³a {res} zosta³y opublikowane jako {published}.',
  'There are no resources to publish.' => 'Nie ma ¿adnych Ÿróde³ do opublikowania.',
);
