<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Can\'t find published assets for Aii Audio Player extension.' 
  => 'Can\'t find published assets for Aii Audio Player extension.',
  'JS player file setted by "playerJSFile" property can\'t be empty.' => 
  'JS player file setted by "playerJSFile" property can\'t be empty.',
  'Property "height" can\'t be empty.' 
  => 'Property "height" can\'t be empty.',
  'Property "width" can\'t be empty.' 
  => 'Property "width" can\'t be empty.',
  'SWF player file setted by "playerSWFFile" property can\'t be empty.' => 
  'SWF player file setted by "playerSWFFile" property can\'t be empty.',
);
